version: '2.4'
services:
  app0:
    image: helloword_01
    container_name: container_01
    build: .
    ports:
      - "4000:8081"
      - "4001:8081"
    restart: always
    # depends_on:
    #   - database
    environment:
      - PORT=8081
    volumes:
      - "/Users/apple/Documents/git/data/logs:/usr/src/app/logs"
    networks:
      - backend
  app1:
    build: .
    image: helloword_02
    container_name: container_02
    ports:
      - "4002:3000"
    environment:
      - PORT=3000
    restart: always
    networks:
      - backend
  app2:
    build: .
    image: helloword_03
    container_name: container_03
    ports:
      - "4003:3000"
    environment:
      - PORT=3000
    restart: always
    networks:
      - backend
networks:
  backend:
    external: true